---
- name: Install ganglia monitor (Ubuntu)
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  become: yes
  with_items:
    - ganglia-monitor
  when: is_debian_or_ubuntu
  tags:
    - ganglia

- name: Configure gmond
  become: yes
  template: src=gmond.conf.j2 dest=/etc/ganglia/gmond.conf
  notify:
    - restart gmond
  tags:
    - ganglia
    - gmond
