---
- name: Init OS for Ganglia playbooks
  hosts:
    - ganglia_master
    - ganglia_monitor
  tasks:
    - include: common/tasks/init-{{ansible_os_family}}.yml
  tags:
    - ganglia

- name: Ganglia frontend/collector (server) Playbook
  hosts: ganglia_master
  roles:
    - ganglia-server
  tags:
    - ganglia

- name: Ganglia monitor (client) Playbook
  hosts: ganglia_monitor
  roles:
    - ganglia-client
  tags:
    - ganglia
